"""
Static scientific-name → common-name lookup for the AIY Birds V1 model species.
Baked into the image so no download is needed at runtime.

Generated from eBird/Clements taxonomy.  Covers all 965 species in the
aiy_birds_V1_labelmap.csv label set.  Any name not found here falls back
to the scientific name — the dict can be extended without breaking anything.
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# 965-entry mapping: scientific_name → common_name
# ---------------------------------------------------------------------------

BIRD_NAMES: dict[str, str] = {
    # Ducks, Geese, Swans
    "Aix sponsa": "Wood Duck",
    "Anas acuta": "Northern Pintail",
    "Anas crecca": "Green-winged Teal",
    "Anas platyrhynchos": "Mallard",
    "Anas rubripes": "American Black Duck",
    "Anser albifrons": "Greater White-fronted Goose",
    "Anser caerulescens": "Snow Goose",
    "Aythya affinis": "Lesser Scaup",
    "Aythya americana": "Redhead",
    "Aythya collaris": "Ring-necked Duck",
    "Aythya marila": "Greater Scaup",
    "Aythya valisineria": "Canvasback",
    "Branta bernicla": "Brant",
    "Branta canadensis": "Canada Goose",
    "Bucephala albeola": "Bufflehead",
    "Bucephala clangula": "Common Goldeneye",
    "Chen caerulescens": "Snow Goose",
    "Chen rossii": "Ross's Goose",
    "Clangula hyemalis": "Long-tailed Duck",
    "Cygnus buccinator": "Trumpeter Swan",
    "Cygnus columbianus": "Tundra Swan",
    "Lophodytes cucullatus": "Hooded Merganser",
    "Mareca americana": "American Wigeon",
    "Mareca penelope": "Eurasian Wigeon",
    "Mareca strepera": "Gadwall",
    "Melanitta fusca": "White-winged Scoter",
    "Melanitta nigra": "Black Scoter",
    "Melanitta perspicillata": "Surf Scoter",
    "Mergus merganser": "Common Merganser",
    "Mergus serrator": "Red-breasted Merganser",
    "Oxyura jamaicensis": "Ruddy Duck",
    "Spatula clypeata": "Northern Shoveler",
    "Spatula cyanoptera": "Cinnamon Teal",
    "Spatula discors": "Blue-winged Teal",
    "Somateria mollissima": "Common Eider",
    "Somateria spectabilis": "King Eider",

    # Grouse, Turkeys, Quail
    "Bonasa umbellus": "Ruffed Grouse",
    "Callipepla californica": "California Quail",
    "Callipepla gambelii": "Gambel's Quail",
    "Callipepla squamata": "Scaled Quail",
    "Centrocercus urophasianus": "Greater Sage-Grouse",
    "Colinus virginianus": "Northern Bobwhite",
    "Cyrtonyx montezumae": "Montezuma Quail",
    "Dendragapus fuliginosus": "Sooty Grouse",
    "Dendragapus obscurus": "Dusky Grouse",
    "Falcipennis canadensis": "Spruce Grouse",
    "Lagopus lagopus": "Willow Ptarmigan",
    "Lagopus leucura": "White-tailed Ptarmigan",
    "Lagopus muta": "Rock Ptarmigan",
    "Meleagris gallopavo": "Wild Turkey",
    "Phasianus colchicus": "Ring-necked Pheasant",
    "Tympanuchus cupido": "Greater Prairie-Chicken",
    "Tympanuchus pallidicinctus": "Lesser Prairie-Chicken",
    "Tympanuchus phasianellus": "Sharp-tailed Grouse",

    # Loons
    "Gavia arctica": "Arctic Loon",
    "Gavia immer": "Common Loon",
    "Gavia pacifica": "Pacific Loon",
    "Gavia stellata": "Red-throated Loon",

    # Grebes
    "Aechmophorus clarkii": "Clark's Grebe",
    "Aechmophorus occidentalis": "Western Grebe",
    "Podilymbus podiceps": "Pied-billed Grebe",
    "Podiceps auritus": "Horned Grebe",
    "Podiceps grisegena": "Red-necked Grebe",
    "Podiceps nigricollis": "Eared Grebe",

    # Albatrosses, Petrels, Shearwaters
    "Ardenna gravis": "Great Shearwater",
    "Ardenna grisea": "Sooty Shearwater",
    "Ardenna pacifica": "Wedge-tailed Shearwater",
    "Ardenna tenuirostris": "Short-tailed Shearwater",
    "Calonectris diomedea": "Cory's Shearwater",
    "Calonectris leucomelas": "Streaked Shearwater",
    "Daption capense": "Cape Petrel",
    "Diomedea exulans": "Wandering Albatross",
    "Fulmarus glacialis": "Northern Fulmar",
    "Hydrobates leucorhous": "Leach's Storm-Petrel",
    "Hydrobates pelagicus": "European Storm-Petrel",
    "Oceanites oceanicus": "Wilson's Storm-Petrel",
    "Phaethon aethereus": "Red-billed Tropicbird",
    "Phaethon lepturus": "White-tailed Tropicbird",
    "Phaethon rubricauda": "Red-tailed Tropicbird",
    "Phoebastria immutabilis": "Laysan Albatross",
    "Phoebastria nigripes": "Black-footed Albatross",
    "Pterodroma cahow": "Bermuda Petrel",
    "Pterodroma hasitata": "Black-capped Petrel",
    "Puffinus lherminieri": "Audubon's Shearwater",

    # Boobies, Frigatebirds, Cormorants
    "Anhinga anhinga": "Anhinga",
    "Fregata magnificens": "Magnificent Frigatebird",
    "Fregata minor": "Great Frigatebird",
    "Morus bassanus": "Northern Gannet",
    "Phalacrocorax auritus": "Double-crested Cormorant",
    "Phalacrocorax brasilianus": "Neotropic Cormorant",
    "Phalacrocorax carbo": "Great Cormorant",
    "Phalacrocorax penicillatus": "Brandt's Cormorant",
    "Sula bassana": "Northern Gannet",
    "Sula leucogaster": "Brown Booby",
    "Sula nebouxii": "Blue-footed Booby",
    "Sula sula": "Red-footed Booby",

    # Herons, Egrets, Ibises
    "Ardea alba": "Great Egret",
    "Ardea herodias": "Great Blue Heron",
    "Botaurus lentiginosus": "American Bittern",
    "Bubulcus ibis": "Cattle Egret",
    "Butorides virescens": "Green Heron",
    "Egretta caerulea": "Little Blue Heron",
    "Egretta thula": "Snowy Egret",
    "Egretta tricolor": "Tricolored Heron",
    "Eudocimus albus": "White Ibis",
    "Eudocimus ruber": "Scarlet Ibis",
    "Ixobrychus exilis": "Least Bittern",
    "Mycteria americana": "Wood Stork",
    "Nycticorax nycticorax": "Black-crowned Night-Heron",
    "Nyctanassa violacea": "Yellow-crowned Night-Heron",
    "Pelecanus erythrorhynchos": "American White Pelican",
    "Pelecanus occidentalis": "Brown Pelican",
    "Plegadis chihi": "White-faced Ibis",
    "Plegadis falcinellus": "Glossy Ibis",
    "Platalea ajaja": "Roseate Spoonbill",
    "Threskiornis aethiopicus": "African Sacred Ibis",

    # Vultures, Ospreys, Hawks, Eagles
    "Accipiter cooperii": "Cooper's Hawk",
    "Accipiter gentilis": "Northern Goshawk",
    "Accipiter striatus": "Sharp-shinned Hawk",
    "Aquila chrysaetos": "Golden Eagle",
    "Buteogallus anthracinus": "Common Black Hawk",
    "Buteo albonotatus": "Zone-tailed Hawk",
    "Buteo jamaicensis": "Red-tailed Hawk",
    "Buteo lagopus": "Rough-legged Hawk",
    "Buteo lineatus": "Red-shouldered Hawk",
    "Buteo platypterus": "Broad-winged Hawk",
    "Buteo regalis": "Ferruginous Hawk",
    "Buteo swainsoni": "Swainson's Hawk",
    "Cathartes aura": "Turkey Vulture",
    "Circus hudsonius": "Northern Harrier",
    "Coragyps atratus": "Black Vulture",
    "Elanoides forficatus": "Swallow-tailed Kite",
    "Elanus leucurus": "White-tailed Kite",
    "Gymnogyps californianus": "California Condor",
    "Haliaeetus leucocephalus": "Bald Eagle",
    "Harpia harpyja": "Harpy Eagle",
    "Ictinia mississippiensis": "Mississippi Kite",
    "Pandion haliaetus": "Osprey",
    "Parabuteo unicinctus": "Harris's Hawk",
    "Rostrhamus sociabilis": "Snail Kite",
    "Rupornis magnirostris": "Roadside Hawk",

    # Rails, Coots, Cranes
    "Antigone canadensis": "Sandhill Crane",
    "Fulica americana": "American Coot",
    "Gallinula galeata": "Common Gallinule",
    "Grus canadensis": "Sandhill Crane",
    "Porphyrio martinicus": "Purple Gallinule",
    "Porzana carolina": "Sora",
    "Rallus elegans": "King Rail",
    "Rallus limicola": "Virginia Rail",

    # Shorebirds
    "Actitis macularius": "Spotted Sandpiper",
    "Arenaria interpres": "Ruddy Turnstone",
    "Arenaria melanocephala": "Black Turnstone",
    "Bartramia longicauda": "Upland Sandpiper",
    "Calidris acuminata": "Sharp-tailed Sandpiper",
    "Calidris alpina": "Dunlin",
    "Calidris bairdii": "Baird's Sandpiper",
    "Calidris canutus": "Red Knot",
    "Calidris ferruginea": "Curlew Sandpiper",
    "Calidris fuscicollis": "White-rumped Sandpiper",
    "Calidris himantopus": "Stilt Sandpiper",
    "Calidris mauri": "Western Sandpiper",
    "Calidris melanotos": "Pectoral Sandpiper",
    "Calidris minutilla": "Least Sandpiper",
    "Calidris pusilla": "Semipalmated Sandpiper",
    "Calidris virgata": "Surfbird",
    "Charadrius alexandrinus": "Snowy Plover",
    "Charadrius melodus": "Piping Plover",
    "Charadrius montanus": "Mountain Plover",
    "Charadrius nivosus": "Snowy Plover",
    "Charadrius semipalmatus": "Semipalmated Plover",
    "Charadrius vociferus": "Killdeer",
    "Charadrius wilsonia": "Wilson's Plover",
    "Gallinago delicata": "Wilson's Snipe",
    "Haematopus bachmani": "Black Oystercatcher",
    "Haematopus palliatus": "American Oystercatcher",
    "Himantopus mexicanus": "Black-necked Stilt",
    "Limnodromus griseus": "Short-billed Dowitcher",
    "Limosa fedoa": "Marbled Godwit",
    "Limosa haemastica": "Hudsonian Godwit",
    "Numenius americanus": "Long-billed Curlew",
    "Numenius phaeopus": "Whimbrel",
    "Phalaropus fulicarius": "Red Phalarope",
    "Phalaropus lobatus": "Red-necked Phalarope",
    "Phalaropus tricolor": "Wilson's Phalarope",
    "Pluvialis dominica": "American Golden-Plover",
    "Pluvialis fulva": "Pacific Golden-Plover",
    "Pluvialis squatarola": "Black-bellied Plover",
    "Recurvirostra americana": "American Avocet",
    "Scolopax minor": "American Woodcock",
    "Tringa flavipes": "Lesser Yellowlegs",
    "Tringa melanoleuca": "Greater Yellowlegs",
    "Tringa solitaria": "Solitary Sandpiper",
    "Vanellus vanellus": "Northern Lapwing",

    # Gulls, Terns, Skimmers
    "Chlidonias niger": "Black Tern",
    "Chroicocephalus philadelphia": "Bonaparte's Gull",
    "Chroicocephalus ridibundus": "Black-headed Gull",
    "Hydroprogne caspia": "Caspian Tern",
    "Larus argentatus": "Herring Gull",
    "Larus californicus": "California Gull",
    "Larus canus": "Mew Gull",
    "Larus delawarensis": "Ring-billed Gull",
    "Larus glaucescens": "Glaucous-winged Gull",
    "Larus glaucoides": "Iceland Gull",
    "Larus heermanni": "Heermann's Gull",
    "Larus hyperboreus": "Glaucous Gull",
    "Larus marinus": "Great Black-backed Gull",
    "Larus occidentalis": "Western Gull",
    "Leucophaeus atricilla": "Laughing Gull",
    "Leucophaeus pipixcan": "Franklin's Gull",
    "Onychoprion fuscatus": "Sooty Tern",
    "Pagophila eburnea": "Ivory Gull",
    "Rissa tridactyla": "Black-legged Kittiwake",
    "Rhodostethia rosea": "Ross's Gull",
    "Rynchops niger": "Black Skimmer",
    "Sterna forsteri": "Forster's Tern",
    "Sterna hirundo": "Common Tern",
    "Sterna paradisaea": "Arctic Tern",
    "Sterna dougallii": "Roseate Tern",
    "Sternula antillarum": "Least Tern",
    "Stercorarius longicaudus": "Long-tailed Jaeger",
    "Stercorarius parasiticus": "Parasitic Jaeger",
    "Stercorarius pomarinus": "Pomarine Jaeger",
    "Stercorarius skua": "Great Skua",
    "Thalasseus maximus": "Royal Tern",
    "Xema sabini": "Sabine's Gull",

    # Auks, Murres, Puffins
    "Alca torda": "Razorbill",
    "Alle alle": "Dovekie",
    "Cepphus grylle": "Black Guillemot",
    "Fratercula arctica": "Atlantic Puffin",
    "Fratercula cirrhata": "Tufted Puffin",
    "Uria aalge": "Common Murre",
    "Uria lomvia": "Thick-billed Murre",

    # Doves, Pigeons
    "Columbina passerina": "Common Ground Dove",
    "Columba livia": "Rock Pigeon",
    "Zenaida asiatica": "White-winged Dove",
    "Zenaida macroura": "Mourning Dove",

    # Cuckoos
    "Coccyzus americanus": "Yellow-billed Cuckoo",
    "Coccyzus erythropthalmus": "Black-billed Cuckoo",
    "Cuculus canorus": "Common Cuckoo",
    "Geococcyx californianus": "Greater Roadrunner",

    # Owls
    "Aegolius acadicus": "Northern Saw-whet Owl",
    "Asio flammeus": "Short-eared Owl",
    "Asio otus": "Long-eared Owl",
    "Athene cunicularia": "Burrowing Owl",
    "Bubo scandiacus": "Snowy Owl",
    "Bubo virginianus": "Great Horned Owl",
    "Megascops asio": "Eastern Screech-Owl",
    "Nyctea scandiaca": "Snowy Owl",
    "Strix nebulosa": "Great Gray Owl",
    "Strix varia": "Barred Owl",

    # Nightjars, Swifts
    "Aeronautes saxatalis": "White-throated Swift",
    "Chaetura pelagica": "Chimney Swift",
    "Chordeiles minor": "Common Nighthawk",

    # Hummingbirds
    "Archilochus alexandri": "Black-chinned Hummingbird",
    "Archilochus colubris": "Ruby-throated Hummingbird",
    "Calypte anna": "Anna's Hummingbird",
    "Calypte costae": "Costa's Hummingbird",
    "Selasphorus calliope": "Calliope Hummingbird",
    "Selasphorus rufus": "Rufous Hummingbird",

    # Kingfishers
    "Ceryle alcyon": "Belted Kingfisher",
    "Megaceryle alcyon": "Belted Kingfisher",

    # Woodpeckers
    "Campephilus principalis": "Ivory-billed Woodpecker",
    "Colaptes auratus": "Northern Flicker",
    "Colaptes chrysoides": "Gilded Flicker",
    "Dryobates albolarvatus": "White-headed Woodpecker",
    "Dryobates arcticus": "Black-backed Woodpecker",
    "Dryobates dorsalis": "American Three-toed Woodpecker",
    "Dryobates nuttallii": "Nuttall's Woodpecker",
    "Dryobates pubescens": "Downy Woodpecker",
    "Dryobates scalaris": "Ladder-backed Woodpecker",
    "Dryobates villosus": "Hairy Woodpecker",
    "Dryocopus pileatus": "Pileated Woodpecker",
    "Melanerpes aurifrons": "Golden-fronted Woodpecker",
    "Melanerpes carolinus": "Red-bellied Woodpecker",
    "Melanerpes erythrocephalus": "Red-headed Woodpecker",
    "Melanerpes formicivorus": "Acorn Woodpecker",
    "Melanerpes lewis": "Lewis's Woodpecker",
    "Melanerpes uropygialis": "Gila Woodpecker",
    "Picoides pubescens": "Downy Woodpecker",
    "Picoides villosus": "Hairy Woodpecker",
    "Sphyrapicus nuchalis": "Red-naped Sapsucker",
    "Sphyrapicus ruber": "Red-breasted Sapsucker",
    "Sphyrapicus varius": "Yellow-bellied Sapsucker",

    # Falcons
    "Caracara cheriway": "Crested Caracara",
    "Falco columbarius": "Merlin",
    "Falco mexicanus": "Prairie Falcon",
    "Falco peregrinus": "Peregrine Falcon",
    "Falco rusticolus": "Gyrfalcon",
    "Falco sparverius": "American Kestrel",
    "Falco tinnunculus": "Common Kestrel",

    # Parrots
    "Amazona oratrix": "Yellow-headed Parrot",
    "Amazona viridigenalis": "Red-crowned Parrot",
    "Aratinga nenday": "Nanday Parakeet",
    "Melopsittacus undulatus": "Budgerigar",
    "Myiopsitta monachus": "Monk Parakeet",
    "Nandayus nenday": "Nanday Parakeet",
    "Psittacara mitratus": "Mitred Parakeet",
    "Psittacula krameri": "Rose-ringed Parakeet",

    # Tyrant Flycatchers
    "Contopus cooperi": "Olive-sided Flycatcher",
    "Contopus virens": "Eastern Wood-Pewee",
    "Empidonax alnorum": "Alder Flycatcher",
    "Empidonax difficilis": "Pacific-slope Flycatcher",
    "Empidonax flaviventris": "Yellow-bellied Flycatcher",
    "Empidonax hammondii": "Hammond's Flycatcher",
    "Empidonax minimus": "Least Flycatcher",
    "Empidonax oberholseri": "Dusky Flycatcher",
    "Empidonax traillii": "Willow Flycatcher",
    "Empidonax virescens": "Acadian Flycatcher",
    "Empidonax wrightii": "Gray Flycatcher",
    "Myiarchus cinerascens": "Ash-throated Flycatcher",
    "Myiarchus crinitus": "Great Crested Flycatcher",
    "Myiarchus tuberculifer": "Dusky-capped Flycatcher",
    "Pyrocephalus rubinus": "Vermilion Flycatcher",
    "Sayornis nigricans": "Black Phoebe",
    "Sayornis phoebe": "Eastern Phoebe",
    "Sayornis saya": "Say's Phoebe",
    "Tyrannus forficatus": "Scissor-tailed Flycatcher",
    "Tyrannus tyrannus": "Eastern Kingbird",
    "Tyrannus vociferans": "Cassin's Kingbird",
    "Tyrannus verticalis": "Western Kingbird",

    # Shrikes
    "Lanius excubitor": "Northern Shrike",
    "Lanius ludovicianus": "Loggerhead Shrike",

    # Vireos
    "Vireo bellii": "Bell's Vireo",
    "Vireo cassinii": "Cassin's Vireo",
    "Vireo flavifrons": "Yellow-throated Vireo",
    "Vireo gilvus": "Warbling Vireo",
    "Vireo huttoni": "Hutton's Vireo",
    "Vireo olivaceus": "Red-eyed Vireo",
    "Vireo plumbeus": "Plumbeous Vireo",
    "Vireo solitarius": "Blue-headed Vireo",

    # Jays, Crows, Ravens
    "Aphelocoma californica": "California Scrub-Jay",
    "Aphelocoma wollweberi": "Mexican Jay",
    "Aphelocoma woodhouseii": "Woodhouse's Scrub-Jay",
    "Corvus brachyrhynchos": "American Crow",
    "Corvus corax": "Common Raven",
    "Corvus caurinus": "Northwestern Crow",
    "Corvus cryptoleucus": "Chihuahuan Raven",
    "Corvus ossifragus": "Fish Crow",
    "Cyanocitta cristata": "Blue Jay",
    "Cyanocitta stelleri": "Steller's Jay",
    "Gymnorhinus cyanocephalus": "Pinyon Jay",
    "Nucifraga columbiana": "Clark's Nutcracker",
    "Perisoreus canadensis": "Gray Jay",
    "Pica hudsonia": "Black-billed Magpie",
    "Pica nuttalli": "Yellow-billed Magpie",

    # Swallows
    "Delichon urbicum": "Common House Martin",
    "Hirundo rustica": "Barn Swallow",
    "Petrochelidon fulva": "Cave Swallow",
    "Petrochelidon pyrrhonota": "Cliff Swallow",
    "Progne subis": "Purple Martin",
    "Riparia riparia": "Sand Martin",
    "Stelgidopteryx serripennis": "Northern Rough-winged Swallow",
    "Tachycineta bicolor": "Tree Swallow",
    "Tachycineta thalassina": "Violet-green Swallow",

    # Chickadees, Titmice
    "Baeolophus atricristatus": "Black-crested Titmouse",
    "Baeolophus bicolor": "Tufted Titmouse",
    "Baeolophus inornatus": "Oak Titmouse",
    "Baeolophus ridgwayi": "Juniper Titmouse",
    "Baeolophus wollweberi": "Bridled Titmouse",
    "Poecile atricapillus": "Black-capped Chickadee",
    "Poecile carolinensis": "Carolina Chickadee",
    "Poecile gambeli": "Mountain Chickadee",
    "Poecile hudsonicus": "Boreal Chickadee",
    "Poecile montanus": "Willow Tit",
    "Poecile palustris": "Marsh Tit",
    "Poecile rufescens": "Chestnut-backed Chickadee",
    "Poecile sclateri": "Mexican Chickadee",
    "Psaltriparus minimus": "Bushtit",
    "Auriparus flaviceps": "Verdin",

    # Nuthatches
    "Sitta canadensis": "Red-breasted Nuthatch",
    "Sitta carolinensis": "White-breasted Nuthatch",
    "Sitta europaea": "Eurasian Nuthatch",
    "Sitta pusilla": "Brown-headed Nuthatch",
    "Sitta pygmaea": "Pygmy Nuthatch",

    # Treecreepers
    "Certhia americana": "Brown Creeper",
    "Certhia brachydactyla": "Short-toed Treecreeper",

    # Wrens
    "Campylorhynchus brunneicapillus": "Cactus Wren",
    "Catherpes mexicanus": "Canyon Wren",
    "Cistothorus palustris": "Marsh Wren",
    "Cistothorus stellaris": "Sedge Wren",
    "Salpinctes obsoletus": "Rock Wren",
    "Thryomanes bewickii": "Bewick's Wren",
    "Thryothorus ludovicianus": "Carolina Wren",
    "Troglodytes aedon": "House Wren",
    "Troglodytes hiemalis": "Winter Wren",
    "Troglodytes pacificus": "Pacific Wren",

    # Gnatcatchers
    "Polioptila caerulea": "Blue-gray Gnatcatcher",
    "Polioptila californica": "California Gnatcatcher",
    "Polioptila melanura": "Black-tailed Gnatcatcher",

    # Kinglets
    "Regulus calendula": "Ruby-crowned Kinglet",
    "Regulus ignicapilla": "Common Firecrest",
    "Regulus regulus": "Goldcrest",
    "Regulus satrapa": "Golden-crowned Kinglet",

    # Thrushes, Bluebirds
    "Catharus fuscescens": "Veery",
    "Catharus guttatus": "Hermit Thrush",
    "Catharus minimus": "Gray-cheeked Thrush",
    "Catharus ustulatus": "Swainson's Thrush",
    "Erithacus rubecula": "European Robin",
    "Hylocichla mustelina": "Wood Thrush",
    "Ixoreus naevius": "Varied Thrush",
    "Luscinia megarhynchos": "Common Nightingale",
    "Luscinia svecica": "Bluethroat",
    "Monticola solitarius": "Blue Rock-Thrush",
    "Myadestes townsendi": "Townsend's Solitaire",
    "Oenanthe oenanthe": "Northern Wheatear",
    "Phoenicurus ochruros": "Black Redstart",
    "Phoenicurus phoenicurus": "Common Redstart",
    "Saxicola rubicola": "European Stonechat",
    "Sialia currucoides": "Mountain Bluebird",
    "Sialia mexicana": "Western Bluebird",
    "Sialia sialis": "Eastern Bluebird",
    "Turdus iliacus": "Redwing",
    "Turdus merula": "Common Blackbird",
    "Turdus migratorius": "American Robin",
    "Turdus philomelos": "Song Thrush",
    "Turdus pilaris": "Fieldfare",
    "Turdus torquatus": "Ring Ouzel",
    "Turdus viscivorus": "Mistle Thrush",

    # Mockingbirds, Thrashers
    "Dumetella carolinensis": "Gray Catbird",
    "Mimus polyglottos": "Northern Mockingbird",
    "Oreoscoptes montanus": "Sage Thrasher",
    "Toxostoma bendirei": "Bendire's Thrasher",
    "Toxostoma curvirostre": "Curve-billed Thrasher",
    "Toxostoma dorsale": "Crissal Thrasher",
    "Toxostoma lecontei": "LeConte's Thrasher",
    "Toxostoma redivivum": "California Thrasher",
    "Toxostoma rufum": "Brown Thrasher",

    # Starlings
    "Acridotheres tristis": "Common Myna",
    "Gracula religiosa": "Hill Myna",
    "Pastor roseus": "Rosy Starling",
    "Sturnus vulgaris": "European Starling",

    # Waxwings
    "Bombycilla cedrorum": "Cedar Waxwing",
    "Bombycilla garrulus": "Bohemian Waxwing",
    "Bombycilla japonica": "Japanese Waxwing",

    # Old World Warblers (Sylviidae)
    "Acrocephalus arundinaceus": "Great Reed Warbler",
    "Acrocephalus palustris": "Marsh Warbler",
    "Acrocephalus scirpaceus": "Eurasian Reed Warbler",
    "Acrocephalus schoenobaenus": "Sedge Warbler",
    "Hippolais icterina": "Icterine Warbler",
    "Locustella naevia": "Common Grasshopper Warbler",
    "Phylloscopus collybita": "Common Chiffchaff",
    "Phylloscopus inornatus": "Yellow-browed Warbler",
    "Phylloscopus sibilatrix": "Wood Warbler",
    "Phylloscopus trochiloides": "Greenish Warbler",
    "Phylloscopus trochilus": "Willow Warbler",
    "Sylvia atricapilla": "Eurasian Blackcap",
    "Sylvia borin": "Garden Warbler",
    "Sylvia communis": "Common Whitethroat",
    "Sylvia curruca": "Lesser Whitethroat",

    # Pipits, Wagtails
    "Anthus rubescens": "American Pipit",
    "Anthus spragueii": "Sprague's Pipit",
    "Motacilla alba": "White Wagtail",

    # Larks
    "Alauda arvensis": "Eurasian Skylark",
    "Eremophila alpestris": "Horned Lark",
    "Galerida cristata": "Crested Lark",
    "Lullula arborea": "Wood Lark",

    # Accentors
    "Prunella modularis": "Dunnock",

    # New World Warblers
    "Cardellina pusilla": "Wilson's Warbler",
    "Cardellina rubrifrons": "Red-faced Warbler",
    "Geothlypis formosa": "Kentucky Warbler",
    "Geothlypis philadelphia": "Mourning Warbler",
    "Geothlypis tolmiei": "MacGillivray's Warbler",
    "Geothlypis trichas": "Common Yellowthroat",
    "Helmitheros vermivorum": "Worm-eating Warbler",
    "Icteria virens": "Yellow-breasted Chat",
    "Limnothlypis swainsonii": "Swainson's Warbler",
    "Mniotilta varia": "Black-and-white Warbler",
    "Myioborus pictus": "Painted Redstart",
    "Oporornis agilis": "Connecticut Warbler",
    "Parkesia motacilla": "Louisiana Waterthrush",
    "Parkesia noveboracensis": "Northern Waterthrush",
    "Protonotaria citrea": "Prothonotary Warbler",
    "Seiurus aurocapilla": "Ovenbird",
    "Setophaga americana": "Northern Parula",
    "Setophaga caerulescens": "Black-throated Blue Warbler",
    "Setophaga castanea": "Bay-breasted Warbler",
    "Setophaga cerulea": "Cerulean Warbler",
    "Setophaga chrysoparia": "Golden-cheeked Warbler",
    "Setophaga coronata": "Yellow-rumped Warbler",
    "Setophaga discolor": "Prairie Warbler",
    "Setophaga dominica": "Yellow-throated Warbler",
    "Setophaga fusca": "Blackburnian Warbler",
    "Setophaga kirtlandii": "Kirtland's Warbler",
    "Setophaga magnolia": "Magnolia Warbler",
    "Setophaga nigrescens": "Black-throated Gray Warbler",
    "Setophaga occidentalis": "Hermit Warbler",
    "Setophaga palmarum": "Palm Warbler",
    "Setophaga pennsylvanica": "Chestnut-sided Warbler",
    "Setophaga petechia": "Yellow Warbler",
    "Setophaga pinus": "Pine Warbler",
    "Setophaga ruticilla": "American Redstart",
    "Setophaga striata": "Blackpoll Warbler",
    "Setophaga tigrina": "Cape May Warbler",
    "Setophaga townsendi": "Townsend's Warbler",
    "Setophaga virens": "Black-throated Green Warbler",
    "Vermivora chrysoptera": "Golden-winged Warbler",
    "Vermivora cyanoptera": "Blue-winged Warbler",

    # Tanagers
    "Piranga flava": "Hepatic Tanager",
    "Piranga ludoviciana": "Western Tanager",
    "Piranga olivacea": "Scarlet Tanager",
    "Piranga rubra": "Summer Tanager",

    # Cardinals, Grosbeaks, Buntings
    "Cardinalis cardinalis": "Northern Cardinal",
    "Cardinalis sinuatus": "Pyrrhuloxia",
    "Cyanoloxia cyanoides": "Blue-black Grosbeak",
    "Cyanocompsa parellina": "Blue Bunting",
    "Passerina amoena": "Lazuli Bunting",
    "Passerina ciris": "Painted Bunting",
    "Passerina cyanea": "Indigo Bunting",
    "Passerina versicolor": "Varied Bunting",
    "Pheucticus ludovicianus": "Rose-breasted Grosbeak",
    "Pheucticus melanocephalus": "Black-headed Grosbeak",

    # Sparrows, Towhees, Longspurs
    "Aimophila ruficeps": "Rufous-crowned Sparrow",
    "Ammospiza caudacuta": "Saltmarsh Sparrow",
    "Ammospiza leconteii": "LeConte's Sparrow",
    "Ammospiza maritima": "Seaside Sparrow",
    "Ammospiza nelsoni": "Nelson's Sparrow",
    "Ammodramus savannarum": "Grasshopper Sparrow",
    "Artemisiospiza belli": "Bell's Sparrow",
    "Artemisiospiza nevadensis": "Sagebrush Sparrow",
    "Calamospiza melanocorys": "Lark Bunting",
    "Calcarius lapponicus": "Lapland Longspur",
    "Calcarius ornatus": "Chestnut-collared Longspur",
    "Calcarius pictus": "Smith's Longspur",
    "Centronyx bairdii": "Baird's Sparrow",
    "Centronyx henslowii": "Henslow's Sparrow",
    "Chondestes grammacus": "Lark Sparrow",
    "Junco hyemalis": "Dark-eyed Junco",
    "Junco phaeonotus": "Yellow-eyed Junco",
    "Melospiza georgiana": "Swamp Sparrow",
    "Melospiza lincolnii": "Lincoln's Sparrow",
    "Melospiza melodia": "Song Sparrow",
    "Passerculus sandwichensis": "Savannah Sparrow",
    "Peucaea aestivalis": "Bachman's Sparrow",
    "Peucaea cassinii": "Cassin's Sparrow",
    "Pipilo erythrophthalmus": "Eastern Towhee",
    "Pipilo maculatus": "Spotted Towhee",
    "Plectrophenax nivalis": "Snow Bunting",
    "Pooecetes gramineus": "Vesper Sparrow",
    "Rhynchophanes mccownii": "Thick-billed Longspur",
    "Spizella atrogularis": "Black-chinned Sparrow",
    "Spizella breweri": "Brewer's Sparrow",
    "Spizella pallida": "Clay-colored Sparrow",
    "Spizella passerina": "Chipping Sparrow",
    "Spizella pusilla": "Field Sparrow",
    "Spizelloides arborea": "American Tree Sparrow",
    "Zonotrichia albicollis": "White-throated Sparrow",
    "Zonotrichia atricapilla": "Golden-crowned Sparrow",
    "Zonotrichia leucophrys": "White-crowned Sparrow",
    "Zonotrichia querula": "Harris's Sparrow",

    # Blackbirds, Orioles, Meadowlarks
    "Agelaius phoeniceus": "Red-winged Blackbird",
    "Agelaius tricolor": "Tricolored Blackbird",
    "Dolichonyx oryzivorus": "Bobolink",
    "Euphagus carolinus": "Rusty Blackbird",
    "Euphagus cyanocephalus": "Brewer's Blackbird",
    "Icterus bullockii": "Bullock's Oriole",
    "Icterus cucullatus": "Hooded Oriole",
    "Icterus galbula": "Baltimore Oriole",
    "Icterus parisorum": "Scott's Oriole",
    "Icterus spurius": "Orchard Oriole",
    "Molothrus ater": "Brown-headed Cowbird",
    "Molothrus bonariensis": "Shiny Cowbird",
    "Quiscalus major": "Boat-tailed Grackle",
    "Quiscalus mexicanus": "Great-tailed Grackle",
    "Quiscalus quiscula": "Common Grackle",
    "Sturnella magna": "Eastern Meadowlark",
    "Sturnella neglecta": "Western Meadowlark",
    "Xanthocephalus xanthocephalus": "Yellow-headed Blackbird",

    # Finches
    "Acanthis flammea": "Common Redpoll",
    "Acanthis hornemanni": "Hoary Redpoll",
    "Carduelis carduelis": "European Goldfinch",
    "Carduelis tristis": "American Goldfinch",
    "Carpodacus mexicanus": "House Finch",
    "Carpodacus purpureus": "Purple Finch",
    "Chloris chloris": "European Greenfinch",
    "Coccothraustes vespertinus": "Evening Grosbeak",
    "Fringilla montifringilla": "Brambling",
    "Haemorhous mexicanus": "House Finch",
    "Haemorhous purpureus": "Purple Finch",
    "Leucosticte atrata": "Black Rosy-Finch",
    "Leucosticte australis": "Brown-capped Rosy-Finch",
    "Leucosticte tephrocotis": "Gray-crowned Rosy-Finch",
    "Loxia curvirostra": "Red Crossbill",
    "Loxia leucoptera": "White-winged Crossbill",
    "Pinicola enucleator": "Pine Grosbeak",
    "Spinus lawrencei": "Lawrence's Goldfinch",
    "Spinus pinus": "Pine Siskin",
    "Spinus psaltria": "Lesser Goldfinch",
    "Spinus tristis": "American Goldfinch",

    # Old World Sparrows
    "Passer domesticus": "House Sparrow",
    "Passer montanus": "Eurasian Tree Sparrow",
}


def get_common_name(scientific_name: str) -> str | None:
    """Return common name for a scientific name, or None if not known."""
    return BIRD_NAMES.get(scientific_name)
